name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: debug
      run: |
        id
        which bash
        whoami
        env
        ps -ef
        pwd
        cat /proc/self/uid_map
        cat /proc/self/status
        systemd-detect-virt
    - uses: ./.github/actions/install-dependencies
    - name: configure
      run: |
        autoreconf -v -f --install
        ./autogen.sh --without-selinux --disable-man --with-yescrypt
    - run: make
    - run: make install DESTDIR=${HOME}/rootfs
    - run: sudo make install
    - name: run tests in shell with tty
      shell: 'script -q -e -c "bash {0}"'
      run: |
        cd tests
        sudo ./run_some
        cat testsuite.log

  container-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [alpine, fedora]
    container:
      image: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/install-dependencies
    - name: configure alpine
      if: ${{ matrix.os == 'alpine' }}
      run: |
        autoreconf -v -f --install
        ./autogen.sh --without-selinux --disable-man --disable-nls --with-yescrypt
    - name: configure fedora
      if: ${{ matrix.os == 'fedora' }}
      run: |
        autoreconf -v -f --install
        ./autogen.sh --enable-shadowgrp --enable-man --with-audit \
          --with-sha-crypt --with-bcrypt --with-yescrypt --with-selinux \
          --without-libcrack --without-libpam --enable-shared \
          --with-group-name-max-length=32
    - run: make
